### ISSUE TITLE
https://taiko.app/

### ISSUE THREAD

**Issue by Gerhut** [bui/taiko-web#102]
Hello bui,

Thanks for your fantastic works to the project! I am the owner of the domain <https://taiko.app>, and would like to point to this web app until I have other plans. Currently I have already make a 302 redirect to your current site location in <https://github.com/Elite-Four/taiko.app/blob/master/_redirects>. If you feel OK, I will modify the A record to point to your server's IP address directly.

**Comment by bui** [comment]
Hi @Gerhut 

Thanks for your kind words. You're more than welcome to redirect your domain to my instance of taiko-web, but it would be best if you didn't point it to taiko.bui.pm's IP address since the server will only accept connections for that domain. If you want to set up taiko-web on your own server for taiko.app, please feel free to do so :)

**Comment by Gerhut** [comment]
Thank you for the reply~
