### ISSUE TITLE
Framerate low

### ISSUE THREAD

**Issue by toozdey** [bui/taiko-web#145]
During drumming the framerate for notes is choppy compared to 2-3 weeks ago (less fps). I'm on same hardware and browser. Sorry don't have much details.
```
Taiko-Web version: https://github.com/bui/taiko-web/commit/f24592d4c8c47e7fbd9ec261e7d2676466051f23
URL: https://taiko.bui.pm/
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Screen size: 1858x1009, outer: 1858x1080, ratio: 1.00
Blur performance: 11.1ms, all images: 315ms
Page load: 1.6s
Language: en (en-US, en)
```

**Comment by toozdey** [comment]
If I set screen size smaller it's good.
```
Screen size: 1173x698, outer: 1189x786, ratio: 1.00

```

**Comment by TheFearlessDeath500** [comment]
toozdey, I think I may have an explanation as to why this occurs. Since the game is using a lot of graphics all at once, the game will eventually be choppy at some points. The more space these graphics take up, the more the game will be lagging. As such, yes, it is recommended to play in Windowed Mode for the best non-lagging experience. Sure, it is frustrating but you'll get over it. uwu

**Comment by toozdey** [comment]
Thanks
