### ISSUE TITLE
I'm new and i can't find my custom songs 

### ISSUE THREAD

**Issue by EunicePleb** [bui/taiko-web#366]
I'm new and when i upload a custom song, it works. But after i quit the web and join again,  i can't find the song.. What do i need to do to find it again? i upload the file again and i found my previous song and the one i just upload there. I'm confused pls help!

**Comment by LoveEevee** [comment]
The way it works right now is you have to select the folder with your songs each time you visit the page. The files do not get uploaded to a server, but are instead being read by the game directly from your disk.

At the time when the code was written, the only way to get access to an entire folder of files was [through an `<input>` element](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory), the state of which cannot be saved across sessions. Since then however, [a new way](https://web.dev/file-system-access/) has been implemented in some browsers (chrome, edge, and opera [at the time of writing](https://caniuse.com/native-filesystem-api)) which allows a page to retain access to a folder even after the page is reloaded. I have already tried using the file system api myself and it works great, so I might consider adding it to taiko-web in hopes that it would improve the user experience.

**Comment by LoveEevee** [comment]
#369
