### ISSUE TITLE
BUG:Dpad did'nt Work during gameplay

### ISSUE THREAD

**Issue by erchget** [bui/taiko-web#471]
when i Press Dpad on menu it Work perfectly
but during gameplay it didnt Work please fix it i dont wanna 
use another mapper application ):

**Comment by bui** [comment]
Could you elaborate on "didn't work"? There are three control options for gamepads which you can check and change in the Game Settings menu. Does the d-pad on your controller not respond, or does it play the wrong part of the drum?

**Comment by erchget** [comment]
my dpad not respond

**Comment by erchget** [comment]
here"s the clip

**Comment by erchget** [comment]
noo i cant give the clip sorry

**Comment by tydeFriz** [comment]
```
Taiko-Web version: https://github.com/bui/taiko-web/commit/f45214225b8a74f59aa829d51e06888fdabbb549
URL: https://taiko.bui.pm/
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
Screen size: 1920x927, outer: 1936x1056, ratio: 1.00
Blur performance: 15.7ms, all images: 136ms
Page load: 2.4s
Gamepad #1: 054c-0ce6-Wireless Controller, buttons: 16, axes: 10
Language: en (it-IT, it, en-US, en)
Audio Latency: 0ms, Video Latency: 0ms
Plugins: Change Music Speed, Show BPM, Millisecond Accuracy, ESE (started), Song of the Day (started)
```

**Comment by KatieFrogs** [comment]
Can you try if the D-pad Axis Input plugin listed on this page fixes the problem: [KatieFrogs/taiko-web-plugins](https://github.com/KatieFrogs/taiko-web-plugins)

**Comment by tydeFriz** [comment]
they are all on axis 9, tried on a different tester as well.
each button is a fixed position on that axis, making a full continuous circle of directions starting from the lowest on said axis moves the indicator continuously from bottom to top.

I noticed that setting axis 9 as either (or both) the plugin's settings, the don is actually received. The problem is it happens when the button is released, not when pressed (exept left arrow, that just refuses to exist).

**Comment by tydeFriz** [comment]
can confirm, thanks a lot!
